#3: Proposal to make compatible with sass `@media`. Other refactors and improvements.
zessx/sass-flexbox pull request #4
Opened 2017-08-08 21:40 UTC by blainehansen

extend placeholders now call mixins rather than the other way around; sass is used instead of scss; space-evenly was added to justify-content and align-content; general refactoring and cleaning for DRY code; bumped to 2.0.0 (since there are major api changes), and added blaine hansen to contributors list; changed readme to reflect; added dev directory and dependencies to allow in-package testing; added `.editorconfig` to make github viewing more readable.

2017-08-09 07:40 UTC, zessx commented
Thanks for your PR, and sorry to not have taken the time to update it myself, will review it today.   
I'm not really ok with the SCSS syntax drop (as this is the mainly used one) but we can easily make both versions cohabit.

2017-08-09 12:05 UTC, zessx requested changes
Nothing to say on the code itself, I successfully tested it, thanks!

2017-08-09 12:05 UTC, zessx commented on README.md
Add a block to explain the test procedure:

> ## Testing
> 
> You can test SassFlexbox, using NPM scripts:
> 
> ```
> npm install --only=dev 
> npm run-script output-dev
> # >> dev/output.css
> ```

2017-08-09 12:05 UTC, zessx commented on sass-flexbox.sass
> +$sass-flexbox-rename-map: (nowrap: none, auto: auto, flex-start: start, flex-end: end, center: center, baseline: baseline, space-between: space-between, space-around: space-around, stretch: stretch,
Leave both `.sass`and `.scss` files in the repository.

2017-08-09 12:05 UTC, zessx commented on README.md
> +@import 'whatever/path/to/modules/sass-flexbox'
If we leave both files, the file extension will be required, and it needs to be specified in the documentation:

> Include the file in your project, specifying the extension (either `sass` or `scss`):
> 
> ```sass
> @import 'whatever/path/to/modules/sass-flexbox.sass'
> ```

2017-08-09 20:44 UTC, blainehansen commented
How is this looking now? :)

2017-08-16 13:12 UTC, zessx approved these changes

2017-08-16 13:13 UTC, merged

2017-08-16 13:13 UTC, zessx commented
Fix #3